-- CREATE TABLE ENGINEER(ID INT, NAME CHAR(20), DEPT CHAR(10));
INSERT INTO ENGINEER(NAME,DEPT) VALUES('GM','CES');
INSERT INTO ENGINEER(NAME,DEPT) VALUES('GA','IT');
INSERT INTO ENGINEER(NAME,DEPT) VALUES('GE','EEE');

COMMIT;