---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vol
  namespace: 
  labels:
    type: local
    name: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /mnt
