---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  labels:
    name: postgres
data:
  postgres-user: ZGJ1c2Vy
  postgres-passwd: ZGJwYXNz
  postgres-db: dGVzdGRi
